markdown: rdiscount
highlighter: pygments
permalink: post/:year/:month/:day/:title.html
paginate: 6
paginate_path: page/:num

blog:
    name:                                                JunGu
    description:                                         Android developer, student
    title:                                               JunGu Blog
    url:                                                 http://blog.2dxgujun.com/
    duoshuo:                                             2dxgujun
    tongji:                                              2dxgujun
    qiniu:                                               # 七牛云地址
author:
    name:                                                JunGu
    email:                                               2dxgujun@gmail.com
    weibo:                                               http://weibo.com/2dxgujun
    github:                                              https://github.com/2dxgujun
    logo:                                                /media/avatar.png
    douban:
        name:                                            db2dxgujun
        key:                                             0f93d5c81935559d2ebb81584ba000d7