markdown: rdiscount
pygments: true
safe: true
auto: true
permalink: /:categories/:month-:day-:year/:title.html
name: "Jun Gu's Blog"
markdown: rdiscount

author: "Jun Gu"
description: "记录生活中的点点滴滴,铭刻生命中的些许感动"
keywords: "一点经验,一些体验,收获心得,无言感动"
disqus: "2dxgujun"
mail: "2dxgujun@gmail.com"

links: 
  - title: "Github"
    name: "2dxgujun"
    url: "http://github.com/2dxgujun"
    desc: "My GitHub"

  - title: "Mail"
    name: "2dxgujun@gmail.com"
    url: "mailto:2dxgujun@gmail.com"
    desc: "Mail to Jun Gu"

  - title: "Project"
    name: "2dxgujun.github.com"
    url: "http://github.com/2dxgujun/2dxgujun.github.com"
    desc: "Project@Github"

navigations: 
  - title: Archive
    class: fa fa-list-ul
    href: /archive

  - title: Tags
    class: fa fa-tags
    href: /tags

  - title: About
    class: fa fa-user
    href: /about

  - title: Links
    class: fa fa-link
    href: /links

  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

